version: "3.9"

services:
  mongo:
    restart: always

  server:
    build:
      target: production
    environment:
      NODE_ENV: production
    volumes: []
    restart: always

  client:
    build:
      target: production
    environment:
      NODE_ENV: production
    ports:
      - "${CLIENT_PORT:-5173}:80"
    volumes: []
    depends_on:
      server:
        condition: service_healthy
    restart: always
